// Generated by CoffeeScript 2.0.2
(function() {
  //!/usr/bin/env nodeunit
  var api_key, make_client;

  api_key = process.env['LINODE_API_KEY'];

  if (api_key == null) {
    console.error('Please set LINODE_API_KEY in environment.');
    process.exit(1);
  }

  exports.test_require = function(t) {
    t.doesNotThrow((function() {
      return require('../src/linode-api');
    }));
    return t.done();
  };

  make_client = function() {
    var LinodeClient;
    LinodeClient = (require('../src/linode-api')).LinodeClient;
    return new LinodeClient(api_key);
  };

  exports.test_echo = function(t) {
    var client, msg;
    client = make_client();
    msg = 'hello';
    return client.call('test.echo', {msg}, function(err, res) {
      t.ok(err == null);
      t.ok(res != null);
      t.deepEqual(res, {msg});
      return t.done();
    });
  };

  exports.test_linode_list = function(t) {
    var client;
    client = make_client();
    return client.call('linode.list', {}, function(err, res) {
      t.ok(err == null);
      console.log(`found ${res.length} linodes`);
      return t.done();
    });
  };

}).call(this);
