// Generated by CoffeeScript 2.0.2
(function() {
  //!/usr/bin/env coffee

  // Linode API CLI interface
  // Brian Hammond <brian@fictorial.com> https://github.com/fictorial/linode-api
  var LinodeClient, action, api_key, argv, client, dump_api, i, k, len, opts, params, ref, util, v, x;

  ({LinodeClient, dump_api} = require('linode-api'));

  util = require('util');

  opts = (require('optimist')).usage('Usage: linode-client [-k <api key>] <action> [param=value ...]').string('k');

  argv = opts.argv;

  action = argv._.shift();

  api_key = argv.k || process.env['LINODE_API_KEY'] || '';

  if (api_key.length === 0 && action !== 'user.getapikey') {
    console.error('no api key\n');
    opts.showHelp();
    process.exit(1);
  }

  if (action == null) {
    console.error('nothing to do\n');
    opts.showHelp();
    console.error("<action> is one of the following:\n");
    console.error(dump_api());
    process.exit(1);
  }

  params = {};

  ref = argv._;
  for (i = 0, len = ref.length; i < len; i++) {
    x = ref[i];
    [k, v] = x.split('=');
    params[k] = v;
  }

  client = new LinodeClient(api_key);

  client.call(action, params, function(err, res) {
    if (err != null) {
      console.error(err.toString());
      process.exit(1);
    }
    return console.log(util.inspect(res));
  });

}).call(this);
